arrowParens: always
semi: false
singleQuote: true
trailingComma: all
useTabs: true
xmlWhitespaceSensitivity: ignore
overrides:
  - files:
      - *.json
      - *.yaml
      - *.yml
    options:
      useTabs: false
      tabWidth: 2
